//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Calc.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CalcParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface ICalcListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.constPI"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstPI([NotNull] CalcParser.ConstPIContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.constPI"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstPI([NotNull] CalcParser.ConstPIContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.constE"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstE([NotNull] CalcParser.ConstEContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.constE"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstE([NotNull] CalcParser.ConstEContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNode([NotNull] CalcParser.NodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNode([NotNull] CalcParser.NodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.log_exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLog_exp([NotNull] CalcParser.Log_expContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.log_exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLog_exp([NotNull] CalcParser.Log_expContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.trig_exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrig_exp([NotNull] CalcParser.Trig_expContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.trig_exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrig_exp([NotNull] CalcParser.Trig_expContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp([NotNull] CalcParser.ExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp([NotNull] CalcParser.ExpContext context);
}
